### ISSUE TITLE
Error: Invalid connection options

### ISSUE THREAD

**Issue by wuffo** [aduis/generator-hapi-rest-api#2]
$ node index
c:\Node\Frameworks\Hapi\address_rest_api\node_modules\hapi\node_modules\hoek\lib\index.js:723
    throw new Error(msgs.join(' ') || 'Unknown error');
          ^
Error: Invalid connection options {
  "router": {
    "isCaseSensitive": true,
    "stripTrailingSlash": false
  },
  "routes": {
    "cache": {
      "statuses": [
        200
      ]
    },
    "cors": {
      "origin": [
        "*"
      ],
      "isOriginExposed": true,
      "matchOrigin": true,
      "maxAge": 86400,
      "headers": [
        "Authorization",
        "Content-Type",
        "If-None-Match"
      ],
      "additionalHeaders": [],
      "methods": [
        "GET",
        "HEAD",
        "POST",
        "PUT",
        "PATCH",
        "DELETE",
        "OPTIONS"
      ],
      "additionalMethods": [],
      "exposedHeaders": [
        "WWW-Authenticate",
        "Server-Authorization"
      ],
      "additionalExposedHeaders": [],
      "credentials": false,
      "override": true
    },
    "files": {
      "relativeTo": "."
    },
    "json": {
      "replacer": null,
      "space": null,
      "suffix": null
    },
    "payload": {
      "failAction": "error",
      "maxBytes": 1048576,
      "output": "data",
      "parse": true,
      "timeout": 10000,
      "uploads": "C:/Users/Steve/AppData/Local/Temp"
    },
    "response": {
      "options": {}
    },
    "security": null,
    "state": {
      "parse": true,
      "failAction": "error"
    },
    "timeout": {
      "server": false
    },
    "validate": {
      "options": {}
    }
  },
  "port" ←[31m[1, 2, 3]←[0m: ""
}
←[31m
[1] "port" must be a number
[2] "port" is not allowed to be empty
[3] "port" is not allowed to be empty←[0m
    at Object.exports.assert (c:\Node\Frameworks\Hapi\address_rest_api\node_modules\hapi\node_module
s\hoek\lib\index.js:723:11)
    at Object.exports.assert (c:\Node\Frameworks\Hapi\address_rest_api\node_modules\hapi\lib\schema.
js:15:10)
    at internals.Server.connection (c:\Node\Frameworks\Hapi\address_rest_api\node_modules\hapi\lib\s
erver.js:111:23)
    at Object.<anonymous> (c:\Node\Frameworks\Hapi\address_rest_api\lib\index.js:5:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by rajeshwarpatlolla** [comment]
I too have the same issue.
